# Generated by Django 3.2.9 on 2021-12-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_company'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
