# Generated by Django 3.2.9 on 2021-12-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211210_2129'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is manager'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='job_position',
            field=models.CharField(default='1', max_length=40, verbose_name='job position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='phone_number',
            field=models.CharField(default='1', max_length=30, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
