exclude: venv*, env*, migrations,
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args:
            ["--ignore=F401, F405, F403", "--max-complexity=11"]
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        args:
            [--line-length=120]
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.790'
#    hooks:
#    -   id: mypy
#        args: [--disallow_untyped_defs = True,--ignore-missing-imports]
