# Generated by Django 3.2.9 on 2021-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211204_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcompany',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bankcompany',
            old_name='company_id',
            new_name='company',
        ),
    ]
