# Generated by Django 3.2.9 on 2021-12-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('web_site', models.URLField(verbose_name='website')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('web_site', models.URLField(verbose_name='website')),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='media/logos')),
                ('post_index', models.IntegerField(verbose_name='post index')),
                ('bank', models.ManyToManyField(to='companies.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
